---
steps:
  - label: ":hammer: build"
    command: .buildkite/pipeline.exec.sh
    concurrency: 1
    concurrency_group: primary
    timeout_in_minutes: 20
    branches: master
    env:
      - TERM: xterm-256color
