---
steps:
  - label: ":hammer: build"
    command: .buildkite/pipeline.exec.sh
    concurrency: 1
    concurrency_group: primary
    timeout_in_minutes: 20
    branches: master
    agents:
      os: linux
    plugins:
      docker#v1.4.0:
        image: getnelson/build-env:unstable
        user: builder
        always-pull: true
        environment:
          - SONATYPE_USERNAME
          - SONATYPE_PASSWORD
          - BUILDKITE_COMMIT
          - BUILDKITE_BRANCH
          - BUILDKITE_BUILD_NUMBER
          - COURSIER_PROGRESS=0
        mounts:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/buildkite-agent/.docker:/home/builder/.docker
          - /var/lib/buildkite-agent/sbt:/home/builder/.sbt
          - /var/lib/buildkite-agent/ivy2:/home/builder/.ivy2
