---
steps:
  - label: ":hammer: build"
    command: .buildkite/pipeline.exec.sh
    concurrency: 1
    concurrency_group: primary
    timeout_in_minutes: 20
    branches: master
    plugins:
      docker#v1.4.0:
        image: getnelson/build-env:unstable
        user: builder
      environment:
        - BUILDKITE_COMMIT
        - BUILDKITE_BRANCH
        - BUILDKITE_BUILD_NUMBER
      mounts:
        - /var/run/docker.sock:/var/run/docker.sock
        - /var/lib/buildkite-agent/.docker:/home/builder/.docker
        - /var/lib/buildkite-agent/gpg:/home/builder/.sbt/gpg
        - /var/lib/buildkite-agent/sbt/gpg.sbt:/home/builder/.sbt/1.0/gpg.sbt
        - /var/lib/buildkite-agent/ivy2:/home/builder/.ivy2
    agents:
      os: linux
