---
steps:
  - label: ":hammer: build"
    command: .buildkite/pipeline.exec.sh
    concurrency: 1
    concurrency_group: primary
    timeout_in_minutes: 20
    branches: master
    env:
      - TRAVIS: true # way hacky
      - TRAVIS_COMMIT: "$BUILDKITE_COMMIT"
      - TRAVIS_REPO_SLUG: getnelson/nelson
      - TRAVIS_JOB_NUMBER: "1.1"
      - TRAVIS_BUILD_NUMBER: "$BUILDKITE_BUILD_NUMBER"
