---
steps:
  - label: ":hammer: build"
    command: .buildkite/pipeline.exec.sh
    concurrency: 1
    concurrency_group: primary
    timeout_in_minutes: 20
    branches: master
    plugins:
      docker#v1.4.0:
        image: getnelson/build-env:unstable
        user: builder
    agents:
      os: linux
